### PR TITLE
chore: update to react 16.x

### PR DESCRIPTION
**Pull request by hboylan**
- Reference `react@16.x`
- Generated `yarn.lock`
- Updated `babel-preset-es2015` to `babel-preset-env`

### CODE REVIEW

**Comment by hboylan** [comment]
@coryhouse Do you have any suggestions for this? Looking at the build history, it appears that Travis CI configuration may be flawed since no builds have ever passed.

I'm just trying to get rid of version warnings while using this awesome project in my own.

**Comment by kevcenteno** [comment]
@coryhouse Have you abandoned this project?

**Comment by coryhouse** [comment]
Sorry, yes. We're not longer using Entypo

**Comment by kevcenteno** [comment]
Ah, sad to hear.  I can take over ownership if you want.

**Comment by coryhouse** [comment]
Due to the org name I can't give this repo to ya. I'd suggest forking.

**Comment by kevcenteno** [comment]
That's all good.  I created https://github.com/kevcenteno/react-entypo-icons and published to npm under `react-entypo-icons`.  Do you mind updating your readme to point to my repo?

@hboylan I've integrated your pull request

**Comment by coryhouse** [comment]
Cool, updated. Thanks!

**Pull request closed without merging**
